<?xml version="1.0"?>
<package format="3">
  <name>mrs_multi_uav_trajectory_loader</name>
  <version>0.0.1</version>
  <description>Minimal ROS2 multi-uav trajectory loader.</description>
  <maintainer email="vinkltob@fel.cvut.cz">Tobias Vinklarek</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>ament_cmake</depend>
  <depend>ament_cmake_python</depend>
  <depend>mrs_msgs</depend>
  <depend>std_srvs</depend>
  <depend>mrs_lib</depend>

  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
