trajectory:
  mode: "load"
  frame_id: "local_origin" # this frame is prefixed with UAV_NAME
  dt: 0.2
  loop: false
  use_heading: false
  fly_now: false
  offset: [0.0, 0.0, 0.0, 0.0] # [x, y, z, heading]
