main:
  uav_name_list: [uav64]
  offset: [0.0, 0.0, 0.0, 0.0]      # offset for all trajectories [x,y,z,yaw]
  delay: [0.0]            # delays before calling the service (in seconds)

timeout_for_calling_services: 3     # maximal waiting time for response after calling service

uav64:
  filename: "/sample_trajectories/eight_traj.csv"

loop: true
