main:
  uav_name_list: [uav1, uav2, uav3]
  offset: [0.0, 0.0, 0.0, 0.0]      # offset for all trajectories [x,y,z,heading]
  delay: [0.0, 0.0, 0.0]       # delays before calling the service (in seconds)

timeout_for_calling_services: 3     # maximal waiting time for response after calling service

dt: 0.2

uav1:
  filename: /sample_trajectory/trajectory1.txt

uav2:
  filename: /sample_trajectory/trajectory2.txt

uav3:
  filename: /sample_trajectory/trajectory3.txt
